name: Kurtosis install
inputs:
  version:
    description: 'Version to install'
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
    - name: Install
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        if [ "${{ inputs.version }}" = "latest" ]; then
          sudo apt install kurtosis-cli
        else
          sudo apt install kurtosis-cli=${{ inputs.version }}
        fi
        kurtosis analytics disable
        echo "$(dirname $(which kurtosis))" >> $GITHUB_PATH
    - name: Pull images
      shell: bash
      run: |
        docker pull docker.ethquokkaops.io/kurtosistech/engine:latest
        docker pull docker.ethquokkaops.io/kurtosistech/files-artifacts-expander:latest
        docker pull docker.ethquokkaops.io/kurtosistech/core:latest
        docker pull docker.ethquokkaops.io/timberio/vector:0.45.0-debian
        docker pull docker.ethquokkaops.io/fluent/fluent-bit:4.0.0
        docker pull docker.ethquokkaops.io/alpine:3.17

        docker tag docker.ethquokkaops.io/kurtosistech/engine:latest kurtosistech/engine:latest
        docker tag docker.ethquokkaops.io/kurtosistech/files-artifacts-expander:latest kurtosistech/files-artifacts-expander:latest
        docker tag docker.ethquokkaops.io/kurtosistech/core:latest kurtosistech/core:latest
        docker tag docker.ethquokkaops.io/timberio/vector:0.45.0-debian timberio/vector:0.45.0-debian
        docker tag docker.ethquokkaops.io/fluent/fluent-bit:4.0.0 fluent/fluent-bit:4.0.0
        docker tag docker.ethquokkaops.io/alpine:3.17 alpine:3.17



