name: Kurtosis install
inputs:
  version:
    description: 'Version to install'
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
    - name: Install
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        if [ "${{ inputs.version }}" = "latest" ]; then
          sudo apt install kurtosis-cli
        else
          sudo apt install kurtosis-cli=${{ inputs.version }}
        fi
        kurtosis analytics disable
        echo "$(dirname $(which kurtosis))" >> $GITHUB_PATH

        # Get the installed version and save it as an environment variable
        KURTOSIS_VERSION=$(kurtosis version | grep -o 'Version:[[:space:]]*[^[:space:]]*' | cut -d':' -f2 | tr -d ' ')
        echo "KURTOSIS_VERSION=$KURTOSIS_VERSION" >> $GITHUB_ENV
        echo "Installed Kurtosis version: $KURTOSIS_VERSION"

    - name: Pull images
      shell: bash
      run: |
        docker pull docker.ethquokkaops.io/dh/kurtosistech/engine:$KURTOSIS_VERSION
        docker pull docker.ethquokkaops.io/dh/kurtosistech/files-artifacts-expander:$KURTOSIS_VERSION
        docker pull docker.ethquokkaops.io/dh/kurtosistech/core:$KURTOSIS_VERSION
        docker pull docker.ethquokkaops.io/dh/timberio/vector:0.45.0-debian
        docker pull docker.ethquokkaops.io/dh/fluent/fluent-bit:4.0.0
        docker pull docker.ethquokkaops.io/dh/alpine:3.17

        docker tag docker.ethquokkaops.io/dh/kurtosistech/engine:$KURTOSIS_VERSION kurtosistech/engine:$KURTOSIS_VERSION
        docker tag docker.ethquokkaops.io/dh/kurtosistech/files-artifacts-expander:$KURTOSIS_VERSION kurtosistech/files-artifacts-expander:$KURTOSIS_VERSION
        docker tag docker.ethquokkaops.io/dh/kurtosistech/core:$KURTOSIS_VERSION kurtosistech/core:$KURTOSIS_VERSION
        docker tag docker.ethquokkaops.io/dh/timberio/vector:0.45.0-debian timberio/vector:0.45.0-debian
        docker tag docker.ethquokkaops.io/dh/fluent/fluent-bit:4.0.0 fluent/fluent-bit:4.0.0
        docker tag docker.ethquokkaops.io/dh/alpine:3.17 alpine:3.17



