name: Kurtosis install
inputs:
  version:
    description: 'Version to install'
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
    - name: Install
      shell: bash
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        if [ "${{ inputs.version }}" = "latest" ]; then
          sudo apt install kurtosis-cli
        else
          sudo apt install kurtosis-cli=${{ inputs.version }}
        fi
        kurtosis analytics disable
        echo "$(dirname $(which kurtosis))" >> $GITHUB_PATH
    - name: Pull images
      shell: bash
      run: |
        docker pull docker.ethquokkaops.io/kurtosistech/engine:latest
        docker pull docker.ethquokkaops.io/kurtosistech/files-artifacts-expander:latest
        docker pull docker.ethquokkaops.io/kurtosistech/core:latest

        docker tag docker.ethquokkaops.io/kurtosistech/engine:latest kurtosistech/engine:latest
        docker tag docker.ethquokkaops.io/kurtosistech/engine:latest kurtosistech/files-artifacts-expander:latest
        docker tag docker.ethquokkaops.io/kurtosistech/engine:latest kurtosistech/core:latest
